name: Test Visitor Count Lambda

on:
  pull_request:
    branches:
      - main
    paths:
      - "lambdas/visitor/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6.2.0
        with:
          go-version-file: "go.mod"

      - name: Run Unit tests
        working-directory: lambdas/visitor
        run: |
          go test

      - name: Run Integration tests
        working-directory: lambdas/visitor
        run: |
          go test -tags=integration
